### ISSUE TITLE
微博小程序的微博详情页的path值有更新计划吗

### ISSUE THREAD

**Issue by Zhou1eezZZ** [IOriens/mina-wiki#1]
微博小程序的微博详情页的path值有更新计划吗，h5的只要https://m.weibo.cn/detail/博文mid就行了。
希望作者能更新一下小程序的博文详情页的path，谢谢。

**Comment by IOriens** [comment]
@Zhou1eezZZ `pages/index/index?blog_id=4429822996087165` 你试一下

**Comment by Zhou1eezZZ** [comment]
> @Zhou1eezZZ `pages/index/index?blog_id=4381319083256416` 你试一下

可以，老哥你真牛
